module.exports = {
  POPUP_TIMEOUT_MS: 15000,
  BATCH_GAP_MS: 5000,
  MAX_DRIVERS_PER_BATCH: 4,
  SEARCH_RADIUS_KM: 10,
  ROAD_DISTANCE_FUDGE_FACTOR: 1.3,
  ASSUMED_URBAN_SPEED_KMH: 30,
  RIDER_LOCATION_WRITE_THROTTLE_MS: 5000,

  ADMIN_ROLES: ["superadmin", "admin", "executive"],
  BCRYPT_SALT_ROUNDS: 10,
};
